### PR TITLE
Center dots horizontally

### PR DESCRIPTION
**Pull request by rik-dsg**
The dots were pushed to the left and not centered properly. This was more apparent when there were few dots( like 2-3) and the width was set to mobile screen size.

### CODE REVIEW

**Comment by patricktran** [comment]
@darth-rik Thank you, I'll take a look at this.

**Comment by patricktran** [comment]
@darth-rik Can you help me on how to reproduce the issue you are seeing?  Here is a screenshot showing that the dots are still centered... no changes were made to the CSS.

Screen Shot 2021-04-21 at 12 47 33 PM

**Comment by rik-dsg** [comment]
screenshot

This seems strange, but as you can see in the screenshot above, the dots aren't aligned properly without altering the CSS. But this doesn't happen in the original example file, so I guess it must have been a mistake on my part somehow. I'm sorry if I wasted your time. And thanks for making such an awesome component.

**Comment by patricktran** [comment]
No worries, let me know if you still believe this needs to be fixed in react-magic-slider-dots.   If you want, please provide me your website's URL and I can see what's going on.

**Comment by rik-dsg** [comment]
Ok thanks. I'll let you know.

**Pull request closed without merging**
